// mockData.js
export const authors = [
  {
    username: 'RHN-04',
    avatar: '/img/personavatar.png',
    bio: 'biblically accurate blue pear',
    followers: [],
    following: [],
    postsCount: 3,
  },

  {
    username: 'Просто Алина',
    avatar: '/img/personavatar.png',
    bio: 'алина просто',
    followers: [],
    following: [],
    postsCount: 1,
  },

  {
    username: 'G78R6',
    avatar: '/img/personavatar.png',
    bio: 'ме',
    followers: [],
    following: [],
    postsCount: 2,
  },

  {
    username: 'malinkina',
    avatar: '/img/personavatar.png',
    bio: 'literal legend',
    followers: [],
    following: [],
    postsCount: 1,
  },

  {
    username: 'SnezhG',
    avatar: '/img/personavatar.png',
    bio: 'literal legend',
    followers: [],
    following: [],
    postsCount: 0,
  },

  {
    username: 'AUTHOR42',
    avatar: '/img/personavatar.png',
    bio: 'кто',
    followers: [],
    following: [],
    postsCount: 7,
  },
];

export const posts = [
    {
        id: 18,
        images: ['/post-stubs/rhnpic3.jpg'],
        author: authors[0],
        title: 'Ня',
        likes: 10,
        comments: [
          { author: authors[4], text: 'Удручающий вид' }
        ],
        description: 'я гений',
        tags: ['уву', 'милота'],
        date: '2023-01-01T12:00:00Z',
      },
      {
        id: 28,
        images: ['/post-stubs/g78r6pic2.png'],
        author: authors[2],
        title: 'Ня',
        likes: 15,
        comments: [
          { author: authors[0], text: 'Я фанатка' }
        ],
        description: 'я гений',
        tags: ['ня', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 38,
        images: ['/post-stubs/alinapic4.jpg'],
        author: authors[1],
        title: 'Ня',
        likes: 15,
        comments: [],
        description: 'я гений',
        tags: ['уву', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 48,
        images: ['/post-stubs/rhnpic5.png'],
        author: authors[0],
        title: 'Ня',
        likes: 15,
        comments: [],
        description: 'я гений',
        tags: ['ня', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 58,
        images: ['/post-stubs/g78r64.png'],
        author: authors[2],
        title: 'Ня',
        likes: 15,
        comments: [],
        description: 'я гений',
        tags: ['уву', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 68,
        images: ['/post-stubs/evgpic2.png'],
        author: authors[3],
        title: 'Ня',
        likes: 15,
        comments: [],
        description:'я гений',
        tags: ['ня', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 78,
        images: ['/post-stubs/evgpic1.png', '/post-stubs/rhnpic6.png'],
        author: authors[0],
        title: 'Ня',
        likes: 15,
        comments: [
          { author: authors[3], text: 'жесть взяла и украла картинку' },
          { author: authors[4], text: 'Удручающий вид' }
        ],
        description: 'я гений',
        tags: ['уву', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 88,
        images: ['/post-stubs/stub.png'],
        author: authors[5],
        title: 'Ня',
        likes: 15,
        comments: [],
        description: 'я гений',
        tags: ['ня', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 98,
        images: ['/post-stubs/stub.png'],
        author: authors[5],
        title: 'Ня',
        likes: 15,
        comments: [],
        description: 'я гений',
        tags: ['уву', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 108,
        images: ['/post-stubs/stub.png'],
        author: authors[5],
        title: 'Ня',
        likes: 15,
        comments: [],
        description:'я гений',
        tags: ['ня', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 118,
        images: ['/post-stubs/stub.png'],
        author: authors[5],
        title: 'Ня',
        likes: 15,
        comments: [],
        description: 'я гений',
        tags: ['уву', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 128,
        images: ['/post-stubs/stub.png'],
        author: authors[5],
        title: 'Ня',
        likes: 15,
        comments: [],
        description: 'я гений',
        tags: ['ня', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 138,
        images: ['/post-stubs/stub.png'],
        author: authors[5],
        title: 'Ня',
        likes: 15,
        comments: [],
        description:'я гений',
        tags: ['уву', 'милота'],
        date: '2023-01-02T12:00:00Z',
      },
      {
        id: 148,
        images: ['/post-stubs/stub.png'],
        author: authors[5],
        title: 'Ня',
        likes: 15,
        comments: [],
        description: 'я гений',
        tags: ['ня', 'милота'],
        date: '2023-01-02T12:00:00Z',
      }
  ];
  